export const SEO = {
  title: "Template Astro",
  description: "Plantilla para iniciar un proyecto con Astro.",
  author: "edard3v",
  img: "https://res.cloudinary.com/dzuo8j1qg/image/upload/v1733991158/edard3v.jpg",
  keywords: [
    "edard3v",
    "edar",
    "desarrollador web",
    "programación",
    "desarrollo front-end",
    "proyectos web",
    "JavaScript",
    "Astro",
    "TypeScript",
    "aplicaciones web",
    "desarrollo de software",
    "template astro",
    "plantilla astro",
  ],
  base_url: "http://localhost:4321/",
};
